spring:
  application:
    name: smart-fin
  datasource:
    url: jdbc:mariadb://localhost:3306/smart_fin
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  secret: ycXp6n8Z3CCpKVzOQiwqwpxmPByG+9HlpvHKiT19g+xz8uWM85Qv4OjGJro0mOOw
  expiration: 3600
